builders:
  mapperBuilder:
    import: "package:framework_base/mapper_builder.dart"
    builder_factories: ["mapperBuilder"]
    build_extensions: {".dart": [".mapper.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
