name: farmwork_base
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.1
  retrofit: ^4.9.2
  connectivity_plus: ^6.0.3
  geolocator: ^14.0.2
  internet_connection_checker: ^1.0.0+1
  nfc_manager: ^4.1.1
  permission_handler: ^12.0.1
  sensors_plus: ^5.0.0
  supabase_flutter: ^2.12.0
  intl: ^0.20.2
  persian_datetime_picker: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

