name: framework_base
description: "A base Flutter package for building production apps with clean architecture, shared services, theme management, and utility extensions."
version: 0.0.1
homepage: https://your-internal-git/framework_base

environment:
  sdk: ^3.10.4
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.1
  retrofit: ^4.9.2
  connectivity_plus: ^6.0.3
  geolocator: ^14.0.2
  internet_connection_checker: ^1.0.0+1
  nfc_manager: ^4.1.1
  permission_handler: ^12.0.1
  sensors_plus: ^5.0.0
  supabase_flutter: ^2.12.0
  intl: ^0.20.2
  persian_datetime_picker: ^3.1.1
  flutter_riverpod: ^2.4.0
  curl_generator: ^1.0.2
  google_api_availability: ^5.0.1
  device_info_plus: ^11.5.0
  universal_html: ^2.2.4
  cross_file: ^0.3.5+2
  image: ^4.0.0
  media_compressor: ^1.0.1
  analyzer: ^8.0.0
  collection: ^1.18.0
  build: ^4.0.4
  source_gen: ^4.2.0
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
#  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mocktail: ^1.0.4
  build_runner: ^2.11.0
  injectable_generator: ^2.6.2
  lints: ^3.0.0
  test: ^1.25.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

