import 'package:flutter/material.dart';
import 'package:framework_base/framework_base.dart';
import 'package:hugeicons/hugeicons.dart';

class DemoAppButton extends StatelessWidget {
  const DemoAppButton({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        AppText('Buttons Primary Filled', style: Theme.of(context).textLMedium),
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.primaryFilled,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton.icon(type: AppButtonType.primaryFilled, icon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle)),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryFilled,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryFilled,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.primaryFilled,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryFilled,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryFilled,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Primary Ghost', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.primaryGhost,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryGhost,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryGhost,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.primaryGhost,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryGhost,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryGhost,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Primary Outline', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.primaryOutline,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryOutline,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryOutline,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.primaryOutline,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryOutline,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.primaryOutline,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Destructive Filled', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.destructiveFilled,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveFilled,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveFilled,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.destructiveFilled,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveFilled,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveFilled,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Destructive Outline', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.destructiveOutline,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveOutline,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveOutline,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.destructiveOutline,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveOutline,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveOutline,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Destructive Ghost', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.destructiveGhost,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveGhost,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveGhost,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.destructiveGhost,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveGhost,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.destructiveGhost,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Neutral Filled', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.neutralFilled,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralFilled,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralFilled,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.neutralFilled,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralFilled,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralFilled,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Neutral Outline', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.neutralOutline,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralOutline,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralOutline,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.neutralOutline,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralOutline,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralOutline,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        AppText('Buttons Neutral Ghost', style: Theme.of(context).textLMedium),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.neutralGhost,
              size: AppButtonSize.large,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralGhost,
              size: AppButtonSize.medium,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralGhost,
              size: AppButtonSize.small,
              onPressed: () {},
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AppButton(
              type: AppButtonType.neutralGhost,
              size: AppButtonSize.large,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralGhost,
              size: AppButtonSize.medium,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
            AppSize.xsmall.gapWidth,
            AppButton(
              type: AppButtonType.neutralGhost,
              size: AppButtonSize.small,
              text: AppText('شروع فرآیند'),
              prefixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAlertCircle),
              suffixIcon: HugeIcon(icon: HugeIcons.strokeRoundedAdd01),
            ),
          ],
        ),
        AppSize.xsmall.gapHeight,
      ],
    );
  }
}
