
spring.data.mongodb.uri=mongodb://localhost:27017/form-generator-db

spring.application.name=form-generator-service
server.port=8081

logging.level.org.springframework.data.mongodb=DEBUG
# JWT Token Settings
# Access Token validity in milliseconds (2 days = 172800000 ms)
jwt.access-token.expiration=172800000
# Refresh Token validity in milliseconds (7 days = 604800000 ms)
jwt.refresh-token.expiration=604800000
# JWT Secret Key (should be at least 256 bits for HS256)
jwt.secret-key=KpW9lbePzFkQy7hPDrfBOiLCjLi8dyRNOFKn7e0Nlvw=
